repos:
- repo: local
  hooks:
  - id: check-yaml
    name: check-yaml
    entry: check-yaml
    language: python
    types: [yaml]
    stages: [Nonepre-commitNone]
  - id: check-json
    name: check-json
    entry: check-json
    language: python
    types: [json]
    stages: [Nonepre-commitNone]
  - id: check-toml
    name: check-toml
    entry: check-toml
    language: python
    types: [toml]
    stages: [Nonepre-commitNone]
  - id: check-ast
    name: check-ast
    entry: check-ast
    language: python
    types: [python]
    stages: [Nonepre-commitNone]
    #- id: autopep8
    #name: autopep8
    #entry: autopep8
    #language: python
    #types: [python]
    #args: [-a, -i]
    #stages: [commit]
  - id: check-builtin-literals
    name: check-builtin-literals
    entry: check-builtin-literals
    language: python
    types: [python]
    exclude: "asamint/parsers/dcm20*"
    stages: [Nonepre-commitNone]
  - id: check-case-conflict
    name: check-case-conflict
    entry: check-case-conflict
    language: python
    types: [python]
    stages: [Nonepre-commitNone]
  - id: check-merge-conflict
    name: check-merge-conflict
    entry: check-merge-conflict
    language: python
    types: [text]
    stages: [Nonepre-commitNone]
  - id: fix-byte-order-marker
    name: fix-byte-order-marker
    entry: fix-byte-order-marker
    language: python
    types: [python]
    stages: [Nonepre-commitNone]
  - id: mixed-line-ending
    name: mixed-line-ending
    entry: mixed-line-ending
    language: python
    types_or: [c, c++, python]
    stages: [Nonepre-commitNone]
  - id: end-of-file-fixer
    name: end-of-file-fixer
    entry: end-of-file-fixer
    language: python
    types_or: [c, c++, python]
    stages: [Nonepre-commitNone]
  - id: trailing-whitespace-fixer
    name: trailing-whitespace-fixer
    entry: trailing-whitespace-fixer
    language: python
    types_or: [c, c++, python]
    stages: [Nonepre-commitNone]
  - id: reorder-python-imports
    name: reorder-python-imports
    entry: reorder-python-imports
    language: python
    types: [python]
    stages: [Nonepre-commitNone]
  - id: black
    name: black
    entry: black
    language: python
    types: [python]
    stages: [Nonepre-commitNone]
  - id: flake8
    name: flake8
    entry: flake8
    language: python
    types: [python]
    stages: [Nonepre-commitNone]
  - id: pytest-check
    name: pytest-check
    entry: pytest
    language: system
    pass_filenames: false
    always_run: true
    stages: [Nonepre-pushNone]
